
baseURL = "https://letterexplorer.com/"
languageCode = "en-us"
title = "LetterExplorer"
theme = "ananke"
paginate = 12
enableRobotsTXT = true
buildFuture = false

[params]
  mainSections = ["posts"]
